### ISSUE TITLE
panic when the left attribute of w:ind element has negative value

### ISSUE THREAD

**Issue by acomagu** [mattn/docx2md#2]
Thank you for helpful tool!

For example, it panics if the document contains
```xml
            <w:pPr>
                <w:ind left="-360" right="-360"/>
            </w:pPr>
```
.

```
panic: strings: negative Repeat count

goroutine 1 [running]:
strings.Repeat(0x54879c, 0x2, 0xffffffffffffffff, 0x0, 0x0)
        /usr/lib/go/src/strings/strings.go:533 +0x5a9
main.(*file).walk(0xc0001a9cf0, 0xc0001a6de8, 0x574ac0, 0xc000106870, 0x0, 0x0)
        /home/yuki/.local/src/github.com/acomagu/pkgbuilds/docx2md/src/docx2md/main.go:219 +0xeec
main.(*file).walk(0xc0001a9cf0, 0xc0001a7ea8, 0x574ac0, 0xc000106870, 0xc0001262e2, 0x6)
        /home/yuki/.local/src/github.com/acomagu/pkgbuilds/docx2md/src/docx2md/main.go:415 +0xa7f
main.(*file).walk(0xc0001a9cf0, 0xc0001a9038, 0x574ac0, 0xc000106870, 0xc0001263c0, 0x203000)
        /home/yuki/.local/src/github.com/acomagu/pkgbuilds/docx2md/src/docx2md/main.go:442 +0x8b2
main.(*file).walk(0xc0001a9cf0, 0xc00014c700, 0x574ac0, 0xc000106870, 0x12, 0xc0001306e0)
        /home/yuki/.local/src/github.com/acomagu/pkgbuilds/docx2md/src/docx2md/main.go:442 +0x8b2
main.docx2md(0x7fffb3d88a65, 0xc, 0x0, 0x0, 0x0)
        /home/yuki/.local/src/github.com/acomagu/pkgbuilds/docx2md/src/docx2md/main.go:535 +0x6a8
main.main()
        /home/yuki/.local/src/github.com/acomagu/pkgbuilds/docx2md/src/docx2md/main.go:553 +0x148
```

The spec says it can be negative value.

http://officeopenxml.com/WPindentation.php

**Comment by mattn** [comment]
Thank you.
